### ISSUE TITLE
Colour options

### ISSUE THREAD

**Issue by OliPassey** [emanuele-albini/MMM-TFL-Status#2]
Hey, thanks for your work on this, really useful.
Would you consider adding config options for styling?

Ideally want to put a solid colour background behind the text, to make it more readable, but also want to avoid large white patches as i use MM on a large screen.
![image](https://github.com/emanuele-albini/MMM-TFL-Status/assets/7745805/1554d600-9a7c-4a66-854c-6ab812f2d810)

**Comment by emanuele-albini** [comment]
Hi OliPassey, happy to hear that you found this MagicMirror module useful :)

What you are describing is already possible without any change to the module: all the appearance configuration of the module is managed through CSS.

In the case of your specific example, if you wanted to change the background colour of the line status to solid white you can just add the following styling information to your `css/custom.css` CSS configuration file. Have a look at [the official MagicMirror documentation](https://docs.magicmirror.builders/modules/customcss.html) for more info on CSS customisation.

```css
.lineStatus {
  background-color: #FFFFFF;
}
```

If you want to change other CSS classes of [MMM-TFL-Status](https://github.com/emanuele-albini/MMM-TFL-Status) have a look at [`tube_status.css`](https://github.com/emanuele-albini/MMM-TFL-Status/blob/master/tube-status.css). The names of the classes should be pretty intuitive.
