### ISSUE TITLE
Typo in configuration in the readme

### ISSUE THREAD

**Issue by hanseirik** [emanuele-albini/MMM-TFL-Status#3]
Just a notice that in the table of configuration options, the default for Elizabeth line is stated as "elizabeth_line" (underscore, which is wrong) , but in the actual .js it's correctly stated as elizabeth-line (hyphen, which is correct).  Therefor, if you use defaults without any manual config it will work, but if you follow the instructions in the readme / table - then you will have trouble.

**Comment by emanuele-albini** [comment]
Thanks for spotting the typo :) I corrected the readme now.
